# Generated by Django 3.2.7 on 2021-09-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_auto_20210903_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id_PK',
        ),
    ]
