# Generated by Django 3.2.7 on 2021-09-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_auto_20210903_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Product',
            new_name='product',
        ),
    ]
